name: Build RTL-SDR V4

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.18

    steps:
      - name: Install Build Dependencies
      run: |
        apk update
        apk add git cmake make gcc g++ musl-dev libusb-dev libusb-dev-static

